### ISSUE TITLE
theme does not appear in theme chooser preview !

### ISSUE THREAD

**Issue by xeon-zolt** [cyngn/android_packages_themes_Template#12]
i downloaded the cm 12 branch zip changed wallpaper and lockscreen wallpaper and compiled it , 
i installed it on CMOS-12.1 i did not got the preview of the theme but i got theme wallpaper when i choose mix theme 
so my question is how to make theme appear in preview

**Comment by djdarkknight96** [comment]
I do believe you would need a full theme package for them to show.

**Comment by xeon-zolt** [comment]
After I added app theme wallpaper , lockscreen wallpaper and bootanimaton I got it in theme chooser 
I think its related to elements of theme to show as preview in theme chooser
